// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tovkiryixtyyxojmxwes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvdmtpcnlpeHR5eXhvam14d2VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTQ5NjcsImV4cCI6MjA2MzMzMDk2N30.QmNlWAOjjvSAsH4_nRALu_9yHqTtRERLg3KzyY50jKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);